### PR TITLE
Stuff

### PR DESCRIPTION
**Pull request by Sollace**
Most imaginative PR title ever.

Changes:

- Expanded on ApiWorld a bit more
- Made some adjustments to the Stringables in the config system
- Added JsonUtils
- Expanded on BLCommandBase and ApiCommand
- Added some more functionality for Brands in ApiGeneral. You can now check for existing brands and add technical ones that won't show up in the game.
- Added ApiGameRule for getting all the gamerules for a world
- Added ForgeWorld for accessing methods added to the world by Forge. This is mostly for internal use at some later point, it also uses regular reflection for now.
- Started adding packet handling for the ParticlesRegister. Still don't know how to add a packet channel for blazeloader though.

Also something else I've been looking at is making a wrapper for the world. It would essentially add an abstraction layer over the world providing full functionality but in an easier to understand, and fully documented way.

For instance client mods could just do:

   World w = ClientWorld.getClientWorld();

For when you are running on the server or in some place where you get a world you can do:

   World w = WorldPool.unpool(minecraftWorld);

Then the interface for each one is exactly the same. So to get all the Creepers in world you could do:

    List<EntityCreeper> creepers = w.entities.select(EntityCreeper.class).get();

Of just:

    List<EntityCreeper> creepers = w.entities.get(EntityCreeper.class);

Any opinions? Or do you think it would be pointless, or too much to maintain?

### CODE REVIEW

**Comment by Sollace** [comment]
@warriordog 
Ugh. Github put me on your repo again.

Isn't there some way to change the default my one compares to?

**Comment by Sollace** [comment]
Added a commit with some more recent changes.
- Added constructor support to the Access Transformer (and likely the BLOBF table too. It will generate a constructor signature from a class name and an array of parameter class names)
- Updated the Access Transformer Documentation
- Expanded on ApiGameRule
- Added ApiWorldType

**Comment by warriordog** [comment]
I'm on a trip right now, but I will get this on Sunday or Monday.

**Comment by Sollace** [comment]
@warriordog All right then. I'll just add whatever else I can. There are some other changes but they requires Java 8 so I don't know if I can include them yet.

**Comment by warriordog** [comment]
@Sollace 

I'm going to merge these and then move to BlazeLoader fork, but I cant test them right now.  Also while I think an abstraction API would be cool, I did try that once but dropped it because I realized it would be a nightmare to maintain and really should be a different API completely.

**Comment by Sollace** [comment]
@warriordog 
Hm. I think a lot of the difficulty in maintaining it would come in with more complexity. I'd actually already started implementing it (read had it mostly done) when the above question occurred to me.

In designing it I've actually kept it as thin as possible. It's all either a call to the equivalent method on world or to something in our own API. I'd say the main thing in updating it would be changing mcp names.

Also for testing you may have to add a value to TargetType in OBFUtil.

     /**
     * A class constructor
     */
    CONSTRUCTOR("CONSTRUCTOR", "CSTR", "CS");

Sorry. I needed some way to distinguish from a method.

**Pull request merged**
